import math
# FIELD_WIDTH = 7
# FIELD_HEIGHT = 4
# USE_SIMILARITIES = True
USE_SIMILARITIES = False
# USE_DECAY = True
USE_DECAY = False

FIELD_WIDTH = 10
FIELD_HEIGHT = 8

EMPTY_CELL_CHAR = '.'
GATEA_CHAR = '1'
GATEB_CHAR = '2'

ACTIONS_NUMBER = 5

ALPHA = 0.1
# ALPHA = 0.001
# ALPHA = 0.05
SIGMA = 1.0
DISCOUNT_FACTOR = 0.9

MOVE_UP = 0
MOVE_DOWN = 1
MOVE_LEFT = 2
MOVE_RIGHT = 3
DONT_MOVE = 4

GOAL_REWARD = 1.0
NO_REWARD = 0.0

BALL_AT_A = 1
BALL_AT_B = 0

A_X_IND = 0
A_Y_IND = 1

B_X_IND = 2
B_Y_IND = 3

HAS_BALL_INDEX = 4

SHAPING_REWARD = 0.05

GATE_Y_POS = int(math.floor(FIELD_HEIGHT / 2))

GATEA_POS = [[GATE_Y_POS-1,FIELD_WIDTH-1],[GATE_Y_POS,FIELD_WIDTH-1]]
GATEB_POS = [[GATE_Y_POS-1,0],[GATE_Y_POS,0]]

true = True
false = False